/**
 * QVAC SDK Worker Entry (auto-generated)
 * Generated by: @qvac/sdk/commands bundleSdk
 * Plugins: 12
 *
*   - @qvac/sdk/llamacpp-completion/plugin
*   - @qvac/sdk/llamacpp-embedding/plugin
*   - @qvac/sdk/whispercpp-transcription/plugin
*   - @qvac/sdk/bci-whispercpp-transcription/plugin
*   - @qvac/sdk/parakeet-transcription/plugin
*   - @qvac/sdk/nmtcpp-translation/plugin
*   - @qvac/sdk/tts-ggml/plugin
*   - @qvac/sdk/ggml-ocr/plugin
*   - @qvac/sdk/sdcpp-generation/plugin
*   - @qvac/sdk/audiogen-ggml/plugin
*   - @qvac/sdk/ggml-vla/plugin
*   - @qvac/sdk/ggml-classification/plugin
 */

import { initializeWorker, ensureRPCSetup } from "@qvac/sdk/worker-lifecycle";
import { registerPlugin } from "@qvac/sdk/plugins";
import { getServerLogger } from "@qvac/sdk/logging";

import { llmPlugin } from "@qvac/sdk/llamacpp-completion/plugin";
import { embeddingsPlugin } from "@qvac/sdk/llamacpp-embedding/plugin";
import { whisperPlugin } from "@qvac/sdk/whispercpp-transcription/plugin";
import { bciPlugin } from "@qvac/sdk/bci-whispercpp-transcription/plugin";
import { parakeetPlugin } from "@qvac/sdk/parakeet-transcription/plugin";
import { nmtPlugin } from "@qvac/sdk/nmtcpp-translation/plugin";
import { ttsPlugin } from "@qvac/sdk/tts-ggml/plugin";
import { ocrPlugin } from "@qvac/sdk/ggml-ocr/plugin";
import { diffusionPlugin } from "@qvac/sdk/sdcpp-generation/plugin";
import { audioGenPlugin } from "@qvac/sdk/audiogen-ggml/plugin";
import { vlaPlugin } from "@qvac/sdk/ggml-vla/plugin";
import { classificationPlugin } from "@qvac/sdk/ggml-classification/plugin";

const { hasRPCConfig } = initializeWorker();

const logger = getServerLogger();
logger.info("🐻 QVAC Worker (custom bundle)");
logger.info("📦 Plugins: 12");

registerPlugin(llmPlugin);
registerPlugin(embeddingsPlugin);
registerPlugin(whisperPlugin);
registerPlugin(bciPlugin);
registerPlugin(parakeetPlugin);
registerPlugin(nmtPlugin);
registerPlugin(ttsPlugin);
registerPlugin(ocrPlugin);
registerPlugin(diffusionPlugin);
registerPlugin(audioGenPlugin);
registerPlugin(vlaPlugin);
registerPlugin(classificationPlugin);

// Auto-setup RPC if config present
if (hasRPCConfig) {
  ensureRPCSetup();
}
